services:
  - type: web
    name: documentos-converter
    env: node
    rootDir: backend
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiYWM1OGRjMzI1YmFhNDJjNzNiMjZiZmRiZTNlOWE3N2U2MzkzODM0MzBhZTZkNWNjYjc1MjljNTQ1ZTMyYWRjOTkwZDQ0MDFiZTY4Yzc1MWYiLCJpYXQiOjE3NjY5NDQyMTcuNDM0NjkzLCJuYmYiOjE3NjY5NDQyMTcuNDM0Njk0LCJleHAiOjQ5MjI2MTc4MTcuNDI4OTg3LCJzdWIiOiI3Mzc5ODYxOSIsInNjb3BlcyI6WyJ0YXNrLnJlYWQiLCJ0YXNrLndyaXRlIl19.U91I8R86KyaF8CDbdMnUeyhStgWDVG3S1sujtOc8aT_eH5x1hk0agl449AIBZwDsQCGp3_KLaESm4y1PaCALIBCeGWnk_miBi22kzM8OHlNXpA4TK8Y1E8FVGsvPUX3QAu7Vzgwahd2KFi54IXLfjnUAVlXZQjFcckPZwrZFmet62nltAZ4z83DWBEu3y7CCvCdsmE__J9A2HUFJyb7VNaObcyKUPqwePHY6nKsjmJ6kWxVBRYyYTlCYX4_ZgxX_U4jBgqrZRSyeD-wa_Q9vaeP1Ap-RiixUh3_oge-bWV_anNK61A7sRbKN24VVvBr081zCOfwvpPrBw6uE6eeBt5rxpddZB9CDeYWvPV34kqkcmdlJmPsGViIk-IcKdl1mtjzrjsUdBshM_-YlYeXA50XHVFObsnPjQBynHT09V1tsCkkuomhT5LgtRD7qrnbmvnjyZTih61KFcTMk0Tnl-YfmySkHRrFG8KcDM1-HVrJOQPSgzJBmjyVd7orOnlQ_55yl8trJj4MvHWJ60uqwNc8wz1G67adrZ4CnDdE92FjRXt8t5YdjWmSfIzrIZpmDiwd6klBVPGhKKEWJ0nlURf5qLynLl9lujOT__0ge0POfcCIvCBHYfv1wDVaJmzZhBL0Xw0GiJkXVcbM3QukYgg_qXF6nHf1Q5tSUOLHTsvw
        sync: false